### ISSUE TITLE
Add workflow to publish Wiki pages

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/android-templates#119]
## Why

We want to start adding more to our [Wiki section](https://github.com/nimblehq/android-templates/wiki), but GitHub doesn't  support creating pull requests for Wiki pages by default. As we want our Wiki pages to be reviewed before being published, we can make use of this [GitHub Action](https://github.com/marketplace/actions/wiki-page-creator-action).

Basically the idea is as following:

- Add workflow for publishing Wiki pages (Ex: `wiki.yml`)
- Add markdown files that represents the Wiki content (Ex: `Campaign.md`)
- Set environment variables (Ex: `GH_PAT`)

When merging to `main`, then we publish all markdown files to the Wiki section

![image](https://user-images.githubusercontent.com/18277915/130930152-b0dc53e7-9dee-4358-b7b8-ecccf1ec3905.png)

```
name: Publish wiki

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - uses: Decathlon/wiki-page-creator-action@v2.0.0
      env:
        GH_PAT: ${{ secrets.WIKI_ACTION_TOKEN }}
        ACTION_MAIL: dev@nimblehq.co
        ACTION_NAME: team-nimblehq
        OWNER: nimblehq
        REPO_NAME: android-templates
        MD_FOLDER: .github/wiki
        WIKI_PUSH_MESSAGE: Push from Github action
```

Read more: [slides](https://docs.google.com/presentation/d/1ufzlhplThxmn_fRQU06bNusK9AZNeNloXtZ0Zs3ttN4/edit)

## Who Benefits?

@nimblehq/android-chapter
